#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Datumformate
DATUM_ZEIT_FORMAT = '%d.%m.%Y %H:%M'
DATUM_FORMAT = '%d.%m.%Y'

# Kontotypen
KONTO_TYP_AKTIV = 'AKTIV'
KONTO_TYP_PASSIV = 'PASSIV'
KONTO_TYP_AUFWAND = 'AUFWAND'
KONTO_TYP_ERTRAG = 'ERTRAG'
KONTO_TYP_ERFOLGSRECHNUNG = 'ERFOLGSRECHNUNG'
KONTO_TYP_BILANZ = 'BILANZ'

# Zinsusanz
ZINSJAHR = 360
ZINSMONAT = 30
