#!/usr/bin/env python
# -*- coding: utf-8 -*-

# DATE AND TIME
DATE_TIME_FORMAT = '%d.%m.%Y %H:%M'
DATE_FORMAT = '%d.%m.%Y'

DEFAULTS = {
	'CURRENCY': 'CHF',
	'VAT': 0.0
}

ACCOUNT_TYPES = {
	'ASSET': 'AKTIV',
	'LIABILITY': 'PASSIV',
	'EXPENSE': 'AUFWAND',
	'INCOME': 'ERTRAG',
	'INCOME_STATEMENT': 'ERFOLGSRECHNUNG',
	'BALANCE_SHEET': 'BILANZ',
	'PROFIT_CARRYFORWARD': 'GEWINNVORTRAG',
	'INPUT_TAX': 'VORSTEUER',
	'TURNOVER_TAX': 'UMSATZSTEUER'
}

NO_VAT_ACCOUNT_TYPES = [
	ACCOUNT_TYPES['INCOME_STATEMENT'],
	ACCOUNT_TYPES['BALANCE_SHEET']
]

ACCOUNT_ATTRIBUTES = {
	'NAME': 'name',
	'TYPE': 'typ',
	'VAT': 'mwst',
	'CURRENCY': 'waehrung'
}

ACCOUNT_SIDE = {
	'LEFT': [
			ACCOUNT_TYPES['ASSET'],
			ACCOUNT_TYPES['EXPENSE'],
			ACCOUNT_TYPES['INCOME_STATEMENT'],
			ACCOUNT_TYPES['INPUT_TAX']
		],
	'RIGHT': [
			ACCOUNT_TYPES['LIABILITY'],
			ACCOUNT_TYPES['INCOME'],
			ACCOUNT_TYPES['BALANCE_SHEET'],
			ACCOUNT_TYPES['TURNOVER_TAX']
		]
}

POSTING_ATTRIBUTES = {
	'DATE': 'datum',
	'TEXT': 'text',
	'DEBIT': 'soll',
	'CREDIT': 'haben',
	'CURRENCY': 'waehrung'
}

FILE_PATHS = {
	'ACCOUNTS': './data/ACCOUNTS.json',
	'POSTINGS': './data/POSTINGS.json',
}
